In [24]:
import numpy as np
# predicted_labels = np.array([0, 0, 1, 3, 3, 3])
predicted_labels = np.array([0, 1, 2, 3, 3, 4])
explanations = np.array([1, 1, 2, 3, 5, 8])
n_images = len(predicted_labels)
print(n_images)
changes = np.array([i for i in range(1, n_images) if predicted_labels[i] != predicted_labels[i-1]], dtype=int)
changes = np.insert(changes, 0, 0)
print(changes)
changes = np.insert(changes, len(changes), n_images-1)
print(changes)
noise_fraction_changes = changes / (n_images-1)
print(noise_fraction_changes)
print(explanations[changes])

6
[0 1 2 3 5]
[0 1 2 3 5 5]
[0.  0.2 0.4 0.6 1.  1. ]
[1 1 2 3 8 8]


In [19]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])